# Generated by Django 2.2 on 2020-03-21 22:06

import django.core.files.storage
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretImage',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/Users/victor/IdeaProjects/secrets.pws-agency.com/backend/media/images'), upload_to='')),
                ('note', models.CharField(max_length=20000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
