# Generated by Django 2.2 on 2020-03-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200321_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretimage',
            name='note',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
