# Generated by Django 4.2.8 on 2024-09-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_secret_view_time_alter_secretimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretimage',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
