# Generated by Django 4.2.8 on 2024-09-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_secretimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretimage',
            name='filename',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
