name: app
description: Secrets App
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  provider: ^6.1.1
  get_it: ^7.6.7
  uuid: ^4.3.3
  intl: ^0.19.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: ChivoDivo
      fonts:
          - asset: assets/fonts/chivo/Chivo-Thin.ttf
            weight: 100
          - asset: assets/fonts/chivo/Chivo-ThinItalic.ttf
            weight: 100
            style: italic
          - asset: assets/fonts/chivo/Chivo-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/chivo/Chivo-ExtraLightItalic.ttf
            weight: 200
            style: italic
          - asset: assets/fonts/chivo/Chivo-Light.ttf
            weight: 300
          - asset: assets/fonts/chivo/Chivo-LightItalic.ttf
            weight: 300
            style: italic
          - asset: assets/fonts/chivo/Chivo-Regular.ttf
            weight: 400
          - asset: assets/fonts/chivo/Chivo-Italic.ttf
            weight: 400
            style: italic
          - asset: assets/fonts/chivo/Chivo-Medium.ttf
            weight: 500
          - asset: assets/fonts/chivo/Chivo-MediumItalic.ttf
            weight: 500
            style: italic
          - asset: assets/fonts/chivo/Chivo-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/chivo/Chivo-SemiBoldItalic.ttf
            weight: 600
          - asset: assets/fonts/chivo/Chivo-Bold.ttf
            weight: 700
          - asset: assets/fonts/chivo/Chivo-BoldItalic.ttf
            weight: 700
          - asset: assets/fonts/chivo/Chivo-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/chivo/Chivo-ExtraBoldItalic.ttf
            weight: 800
          - asset: assets/fonts/chivo/Chivo-Black.ttf
            weight: 900
          - asset: assets/fonts/chivo/Chivo-BlackItalic.ttf
            weight: 900
    - family: SpaceGrotesk
      fonts:
          - asset: assets/fonts/space_grotesk/SpaceGrotesk-Light.ttf
            weight: 300
          - asset: assets/fonts/space_grotesk/SpaceGrotesk-Regular.ttf
            weight: 400
          - asset: assets/fonts/space_grotesk/SpaceGrotesk-Medium.ttf
            weight: 500
          - asset: assets/fonts/space_grotesk/SpaceGrotesk-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/space_grotesk/SpaceGrotesk-Bold.ttf
            weight: 700

  assets:
    - assets/logo/
    - assets/secret-icons/
