# -*- coding: utf-8 -*-
"""
Django settings for configuration project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
import json
import os
from datetime import timedelta

from django.contrib.messages import constants as messages
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from django.core.exceptions import ImproperlyConfigured

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'jadfsoijfaiodsfjoiano')
SECRETS_FOLDER_PATH = os.path.join(BASE_DIR, 'not_secret')

SEPARATOR = '!)#'
SEPARATOR_REPLACEMENT = '//!//)//#'
ID_LOG_FILE = BASE_DIR + '/id_store.json'

# SECURITY WARNING: don't run with debug turned on in production!
DJANGO_DEBUG = os.environ.get('DJANGO_DEBUG', False)

ALLOWED_HOSTS = ['secrets.pws-agency.com', 'localhost', '127.0.0.1', os.environ.get('DJANGO_ALLOWED_HOSTS',
                                                                                    'pws-secrets.com')]

# Application definition

MESSAGE_TAGS = {
    messages.ERROR: 'danger'
}

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    'bootstrap4',
    'api',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'configuration.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'configuration.context_processors.debug',
            ],
        },
    },
]

WSGI_APPLICATION = 'configuration.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = False
USE_L10N = False
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
    'UNAUTHENTICATED_USER': None
}

KEYFILE_PATH = os.path.join(SECRETS_FOLDER_PATH, 'keys.private')

MAX_EXPIRATION_MINUTES = 60 * 24 * 1

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(SECRETS_FOLDER_PATH, 'unsecreted.db')
    }
}
